name: Mirror external_platform_vanadium

on:
  workflow_dispatch:
  schedule:
    - cron: '26 * * * *'

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@gitlab.com:grapheneos/platform_external_vanadium.git"
          destination-repo: "git@github.com:mbestavros/vanadium-release-mirror.git"
