name: Mirror external_platform_vanadium

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '26 * * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - uses: actions/checkout@v4
      - name: Pull from Gitlab
        run: |
          git remote add vanadium https://gitlab.com/grapheneos/platform_external_vanadium.git
          git fetch vanadium --depth=1
          git cherry-pick vanadium/14
      - name: Push to Github
        run: git push "https://x:${{ secrets.GITHUB_TOKEN }}@github.com/mbestavros/vanadium-release-mirror.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
